import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { GuidelinesForContentCreators } from '../content-type-snippets/guidelines_for_content_creators';
import { ProductStatus } from '../taxonomies/product_status';
import { Sitemap } from '../taxonomies/sitemap_538125f';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Accessory
 * Id: d9748663-f567-4c51-a922-c24a1d6b935a
 * Codename: accessory
 */
export type Accessory = IContentItem<{
  /**
   * Product name (text)
   * Required: false
   * Id: f9e2672c-5035-412e-3985-d6112b3781bd
   * Codename: product_name
   *
   * Include a product display name.
   */
  productName: Elements.TextElement;

  /**
   * Price (number)
   * Required: false
   * Id: 51d63ac3-d40d-15ea-c219-be207714077c
   * Codename: price
   *
   * Include a product price.
   */
  price: Elements.NumberElement;

  /**
   * Image (asset)
   * Required: false
   * Id: f0db12e6-86e4-8597-903b-c5984076d6b3
   * Codename: image
   *
   * Upload one product image; the recommended size is 300 × 300 px.
   */
  image: Elements.AssetsElement;

  /**
   * Manufacturer (text)
   * Required: false
   * Id: ab75ff46-b629-5ce5-aac9-79ed8a7b869c
   * Codename: manufacturer
   *
   * Include a manufacturer's name.
   */
  manufacturer: Elements.TextElement;

  /**
   * Product status (taxonomy)
   * Required: false
   * Id: ef13b1f4-b558-f707-35a4-86146dbe4518
   * Codename: product_status
   *
   * Add a product status if the product is included in a special offering.
   */
  productStatus: Elements.TaxonomyElement<ProductStatus>;

  /**
   * Short description (rich_text)
   * Required: false
   * Id: 9740e2d0-87e8-52f5-ff4c-566fa00b1253
   * Codename: short_description
   *
   * Include a short description that fits within 160 characters.
   */
  shortDescription: Elements.RichTextElement;

  /**
   * Long description (rich_text)
   * Required: false
   * Id: 1f961774-a589-4e21-9f8e-a8c4908ea476
   * Codename: long_description
   *
   * Include a full product description.
   */
  longDescription: Elements.RichTextElement;

  /**
   * URL pattern (url_slug)
   * Required: false
   * Id: 69e4af48-f1ac-1146-e6c9-d20d55ca5792
   * Codename: url_pattern
   *
   * Provide a SEO-friendly URL.
   */
  urlPattern: Elements.UrlSlugElement;

  /**
   * Sitemap (taxonomy)
   * Required: false
   * Id: d8ed1597-930c-4cf8-a34e-c5d5e82718ed
   * Codename: sitemap
   */
  sitemap: Elements.TaxonomyElement<Sitemap>;
}> &
  GuidelinesForContentCreators &
  Metadata;
