import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { GuidelinesForContentCreators } from '../content-type-snippets/guidelines_for_content_creators';
import { ProductStatus } from '../taxonomies/product_status';
import { Sitemap } from '../taxonomies/sitemap_538125f';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Grinder
 * Id: da4f1cb1-8a55-43e5-9fcc-67ad331c8888
 * Codename: grinder
 */
export type Grinder = IContentItem<{
  /**
   * Product name (text)
   * Required: false
   * Id: b7b9604e-c74e-79ea-2a0f-d74d6347e35a
   * Codename: product_name
   *
   * Include a product display name.
   */
  productName: Elements.TextElement;

  /**
   * Price (number)
   * Required: false
   * Id: 1e14595d-7fe8-7765-6df6-fad6a6e4851f
   * Codename: price
   *
   * Include a product price.
   */
  price: Elements.NumberElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 7fe226b9-d21f-80ff-e680-6e6f44ce044b
   * Codename: image
   *
   * Upload one product image; the recommended size is 300 × 300 px.
   */
  image: Elements.AssetsElement;

  /**
   * Manufacturer (text)
   * Required: false
   * Id: 2c389736-7dfa-b03e-8996-7eba451cfdb5
   * Codename: manufacturer
   *
   * Include a manufacturer's name.
   */
  manufacturer: Elements.TextElement;

  /**
   * Product status (taxonomy)
   * Required: false
   * Id: 54120e88-82cc-2202-e72d-9cae0ced3f51
   * Codename: product_status
   *
   * Add a product status if the product is included in a special offering.
   */
  productStatus: Elements.TaxonomyElement<ProductStatus>;

  /**
   * Short description (rich_text)
   * Required: false
   * Id: 23ee310f-9732-9193-ad5e-80f75bfc276d
   * Codename: short_description
   *
   * Include a short description that fits within 160 characters.
   */
  shortDescription: Elements.RichTextElement;

  /**
   * Long description (rich_text)
   * Required: false
   * Id: 21e77286-e87b-d6e3-902d-13b5814b5e75
   * Codename: long_description
   *
   * Include a full product description.
   */
  longDescription: Elements.RichTextElement;

  /**
   * URL pattern (url_slug)
   * Required: false
   * Id: bf6ad588-11e5-ba0d-2c18-ccd50064a32a
   * Codename: url_pattern
   *
   * Provide a SEO-friendly URL.
   */
  urlPattern: Elements.UrlSlugElement;

  /**
   * Sitemap (taxonomy)
   * Required: false
   * Id: 02f0e374-6760-4b4d-99a8-60485572b764
   * Codename: sitemap
   */
  sitemap: Elements.TaxonomyElement<Sitemap>;
}> &
  GuidelinesForContentCreators &
  Metadata;
