/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Project name: Sample Project 8/17/2022, 2:33:56 PM
 * Environment: Production
 * Project Id: 24b5af12-5cf1-0044-2ffb-55e16103a4d6
 */
export const assetFolders = {
  /**
   * Café locations
   */
  caféLocations: {
    id: '958001d8-2228-4373-b966-5262b5b96f71',
    name: 'Café locations',
    externalId: undefined,
    folders: {},
  },
};
