/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Project name: Sample Project 8/17/2022, 2:33:56 PM
 * Environment: Production
 * Project Id: 24b5af12-5cf1-0044-2ffb-55e16103a4d6
 */
export const collections = {
  /**
   * Default
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
};
