/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Project name: Sample Project 8/17/2022, 2:33:56 PM
 * Environment: Production
 * Project Id: 24b5af12-5cf1-0044-2ffb-55e16103a4d6
 */
export const roles = {
  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: 'aca6ceab-8078-4b66-86b9-8dee5ccb3c25',
    name: 'Project manager',
  },
};
