/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Project name: Sample Project 8/17/2022, 2:33:56 PM
 * Environment: Production
 * Project Id: 24b5af12-5cf1-0044-2ffb-55e16103a4d6
 */
export const workflows = {
  /**
   * Default
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: b4363ccd-8f21-45fd-a840-5843d7b7f008
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
};
